### ISSUE TITLE
FRONTEND:  (ALBUMS PAGE) have uniform effect for album titles with different length + fix formatting of albums when filtering

### ISSUE THREAD

**Issue by shaaronl** [shaaronl/jukeboxd#115]
COMPLETED? -- looks good on my end! thank you tammy!!

suggestions: only suggesstion is that when filtering, the text input is white so i'd suggest changing the color for better visibility (easy fix)

**Comment by shaaronl** [comment]
<img width="1440" alt="Screen Shot 2024-06-03 at 8 31 38 AM" src="https://github.com/shaaronl/jukeboxd/assets/72675377/be5b4898-06c6-4835-87af-0ba537a040a6">
<img width="1440" alt="Screen Shot 2024-06-03 at 8 31 47 AM" src="https://github.com/shaaronl/jukeboxd/assets/72675377/21b21177-a56e-447b-9af1-f1e28c3e34fa">
<img width="1440" alt="Screen Shot 2024-06-03 at 8 32 23 AM" src="https://github.com/shaaronl/jukeboxd/assets/72675377/9aff8a76-401a-4f51-abcd-adbe39866135">

formatting looks clean!

**Comment by saravoong** [comment]
It seems that you're in dark mode, so the text is white
